### ISSUE TITLE
Learn Go

### ISSUE THREAD

**Issue by PsuJap91** [PSUSWENG894/TravisCI-Lambda#11]
[Go](https://golang.org/) is the programming language of choice for this project. As such we all must learn how to code in this language.

**Comment by PsuJap91** [comment]
https://medium.com/quick-code/top-online-courses-to-learn-go-programming-language-golang-for-beginners-c228c615946c

**Comment by PsuJap91** [comment]
https://github.com/golang/go/wiki/Learn

**Comment by PsuJap91** [comment]
https://www.pluralsight.com/learn

**Comment by evensteven01** [comment]
This is useful. We should follow Go convention.
https://github.com/golang-standards/project-layout
