### ISSUE TITLE
Configure an AWS account that all devs can access

### ISSUE THREAD

**Issue by evensteven01** [PSUSWENG894/TravisCI-Lambda#57]
Use Case: AWS to host Lambdas and test Alexa
Actor: Development Team
Basic Flow:
AWS will be where we store the Lambda function that controls the functionality of our Alexa skill. We need to set up an AWS account (using the AWS Educate to get $100 free credit). Its important for all devs to be able to access.

**Comment by evensteven01** [comment]
I've managed to create an AWS Educate account, which I connected to my personal AWS user. I've redeemed the $100 credit. I now want to validate:
1) That this was the correct way to do this (since right now I'm starting configuration within my account)
2) How to give you all access to everything related to our Alexa skill (but none of my personal stuff)

**Comment by evensteven01** [comment]
This might be the way to go.
https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

Alternatively, Cloud9 or Resource Groups might work, but both seem a bit more difficult.

**Comment by PsuJap91** [comment]
Joseph, Mike and Randy can all see the build

**Comment by evensteven01** [comment]
After further research, I found a few options.
1) I allow my team members to access AWS resources on my account by setting up roles and policies on my account, and then them creating IAM users on their own account.
2) I allow my team members to access AWS resources on my account by setting up roles and policies on my account, and then I create IAM users on my account for them.
3) I create a new separate account for this project, create IAM users for each of us. I then share IAM user credentials for each, and the root account's credentials with everyone.

Option 3 is ideal, but I am not easily able to transfer my credits.
Option 1 requires more work from my team members, and will require more collaboration to test if I've set things up properly.

I decided on Option 2, as I can allow access to my team members, while first testing on my own whether this will work. If this turns out to be ideal, we could potentially be able to migrate to option 3, by reaching out to AWS to have them transfer credits.

**Comment by evensteven01** [comment]
For setting up the roles and polices in my account, I followed this:
https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html

After starting it, I decided to go the route of IAM users in my local account, which I'm using this tutorial:
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_users_create.html

**Comment by evensteven01** [comment]
For the actual Alexa skill, this is not in AWS console, but rather in Amazon Developr account
This has a separate user permissions
https://developer.amazon.com/userpermissions/detail.html
Following instructions on
https://developer.amazon.com/docs/app-submission/manage-account-and-permissions.html#add_other_users
To give access to other users

**Comment by evensteven01** [comment]
In order to give everyone maximum control over AWS, while not putting my own AWS account at risk, I created a new account for the group. Since it is required to put a credit card down, I will still be the root account owner. But I am able to give everyone else Admin access, which they can access any resources with. The only restriction is the access to billing.

**Comment by evensteven01** [comment]
It will be important that we be mindful of charges, since they would be charged to my credit card. Please read charging details for any services we add/use.

**Comment by evensteven01** [comment]
I am currently waiting to see if Amazon will transfer my credits from my personal account to this new account, since I had originally redeemed my credits on my personal account.

**Comment by evensteven01** [comment]
Everyone confirmed access.
